bet365NameChanges = {'BOS Celtics' : 'Boston Celtics',
                     'DEN Nuggets' : 'Denver Nuggets',
                     'PHI 76ers' : 'Philadelphia 76ers',
                     'CLE Cavaliers' : 'Cleveland Cavaliers',
                     'LA Lakers' : 'Los Angeles Lakers',
                     'ATL Hawks' : 'Atlanta Hawks',
                     'CHI Bulls' : 'Chicago Bulls',
                     'POR TrailBlazers' : 'Portland Trailblazers',
                     'OKC Thunder' : 'Oklahoma City Thunder',
                     'SA Spurs' : 'San Antonio Spurs',
                     'PHX Suns' : 'Phoenix Suns',
                     'LA Clippers' : 'Los Angeles Clippers',
                     'MEM Grizzlies' : 'Memphis Grizzlies',
                     'NO Pelicans' : 'New Orlean Pelicans',
                     'SAC Kings' : 'Sacramento Kings',
                     'TOR Raptors' : 'Toronto Raptors',
                     'MIN Timberwolves' : 'Minnesota Timberwolves',
                     'UTA Jazz' : 'Utah Jazz',
                     'ORL Magic' : 'Orlando Magic',
                     'DET Pistons' : 'Detroit Pistons',
                     'MIL Bucks' : 'Milwaukee Bucks',
                     'GS Warriors' : 'Golden State Warriors',
                     'DAL Mavericks' : 'Dallas Mavericks',
                     'MIA Heat' : 'Miami Heat',
                     'BKN Nets' : 'Brooklyn Nets',
                     'NY Knicks' : 'New York Knicks',
                     'IND Pacers' : 'Indianna Pacers',
                     'WAS Wizards' : 'Washington Wizards',
                     'CHA Hornets' : 'Charlotte Hornets',
                     'HOU Rockets' : 'Houston Rockets',
                     }
