bet365NameChanges = {'BOS Celtics' : 'Boston Celtics',
                     'DEN Nuggets' : 'Denver Nuggets',
                     'PHI 76ers' : 'Philadelphia 76ers',
                     'CLE Cavaliers' : 'Cleveland Cavaliers',
                     'LA Lakers' : 'Los Angeles Lakers',
                     'ATL Hawks' : 'Atlanta Hawks',
                     'CHI Bulls' : 'Chicago Bulls',
                     'POR Trail Blazers' : 'Portland Trail Blazers',
                     'OKC Thunder' : 'Oklahoma City Thunder',
                     'SA Spurs' : 'San Antonio Spurs',
                     'PHX Suns' : 'Phoenix Suns',
                     'LA Clippers' : 'Los Angeles Clippers',
                     'MEM Grizzlies' : 'Memphis Grizzlies',
                     'NO Pelicans' : 'New Orleans Pelicans',
                     'SAC Kings' : 'Sacramento Kings',
                     'TOR Raptors' : 'Toronto Raptors',
                     'MIN Timberwolves' : 'Minnesota Timberwolves',
                     'UTA Jazz' : 'Utah Jazz',
                     'ORL Magic' : 'Orlando Magic',
                     'DET Pistons' : 'Detroit Pistons',
                     'MIL Bucks' : 'Milwaukee Bucks',
                     'GS Warriors' : 'Golden State Warriors',
                     'DAL Mavericks' : 'Dallas Mavericks',
                     'MIA Heat' : 'Miami Heat',
                     'BKN Nets' : 'Brooklyn Nets',
                     'NY Knicks' : 'New York Knicks',
                     'IND Pacers' : 'Indiana Pacers',
                     'WAS Wizards' : 'Washington Wizards',
                     'CHA Hornets' : 'Charlotte Hornets',   
                     'HOU Rockets' : 'Houston Rockets',
                     }

sportsInteractionNameChanges = {'LA Lakers': 'Los Angeles Lakers',
                                'LA Clippers': 'Los Angeles Clippers',
                                'Oklahoma City': 'Oklahoma City Thunder',
                                }

sportsInteractionTeamChanges = {'76ers': 'Philadelphia 76ers',
                                'Pacers': 'Indiana Pacers',
                                'Celtics': 'Boston Celtics',
                                'Cavaliers': 'Cleveland Cavaliers',
                                'Trail Blazers': 'Portland Trail Blazers',
                                'Pistons': 'Detroit Pistons',
                                'Hawks': 'Atlanta Hawks',
                                'Heat': 'Miami Heat',
                                'Raptors': 'Toronto Raptors',
                                'Nuggets': 'Denver Nuggets',
                                'Pelicans': 'New Orleans Pelicans',
                                'Kings': 'Sacramento Kings',
                                'Clippers': 'Los Angeles Clippers',
                                'Bulls': 'Chicago Bulls',
                                'Thunder': 'Oklahoma City Thunder',
                                'Suns': 'Phoenix Suns',
                                'Mavericks': 'Dallas Mavericks',
                                'Wizards': 'Washington Wizards',
                                }

teams = {'Boston Celtics' : 'Celtics',
         'Denver Nuggets' : 'Nuggets',
         'Philadelphia 76ers' : '76ers',
         'Cleveland Cavaliers' : 'Cavaliers',
         'Los Angeles Lakers' : 'Lakers',
         'Atlanta Hawks' : 'Hawks',
         'Chicago Bulls' : 'Bulls',
         'Portland Trail Blazers' : 'Trail Blazers',
         'Oklahoma City Thunder' : 'Thunder',
         'San Antonio Spurs' : 'Spurs',
         'Phoenix Suns' : 'Suns',
         'Los Angeles Clippers' : 'Clippers',
         'Memphis Grizzlies' : 'Grizzlies',
         'New Orleans Pelicans' : 'Pelicans',
         'Sacramento Kings' : 'Kings',
         'Toronto Raptors' : 'Raptors',
         'Minnesota Timberwolves' : 'Timberwolves',
         'Utah Jazz' : 'Jazz',
         'Orlando Magic' : 'Magic',
         'Detroit Pistons' : 'Pistons',
         'Milwaukee Bucks' : 'Bucks',
         'Golden State Warriors' : 'Warriors',
         'Dallas Mavericks' : 'Mavericks',
         'Miami Heat' : 'Heat',
         'Brooklyn Nets' : 'Nets',
         'New York Knicks' : 'Knicks',
         'Indiana Pacers' : 'Pacers',
         'Washington Wizards' : 'Wizards',
         'Charlotte Hornets' : 'Hornets',   
         'Houston Rockets' : 'Rockets',
        }

cities = {'Boston Celtics' : 'Boston',
         'Denver Nuggets' : 'Denver',
         'Philadelphia 76ers' : 'Philadelphia',
         'Cleveland Cavaliers' : 'Cleveland',
         'Los Angeles Lakers' : 'Los Angeles',
         'Atlanta Hawks' : 'Atlanta',
         'Chicago Bulls' : 'Chicago',
         'Portland Trail Blazers' : 'Portland',
         'Oklahoma City Thunder' : 'Oklahoma City',
         'San Antonio Spurs' : 'San Antonio',
         'Phoenix Suns' : 'Phoenix',
         'Los Angeles Clippers' : 'Los Angeles',
         'Memphis Grizzlies' : 'Grizzlies',
         'New Orleans Pelicans' : 'New Orleans',
         'Sacramento Kings' : 'Sacramento',
         'Toronto Raptors' : 'Toronto',
         'Minnesota Timberwolves' : 'Minnesota',
         'Utah Jazz' : 'Utah',
         'Orlando Magic' : 'Orlando',
         'Detroit Pistons' : 'Detroit',
         'Milwaukee Bucks' : 'Milwaukee',
         'Golden State Warriors' : 'Golden State',
         'Dallas Mavericks' : 'Dallas',
         'Miami Heat' : 'Miami',
         'Brooklyn Nets' : 'Brooklyn',
         'New York Knicks' : 'New York',
         'Indiana Pacers' : 'Indiana',
         'Washington Wizards' : 'Washington',
         'Charlotte Hornets' : 'Charlotte',   
         'Houston Rockets' : 'Houston',
        }



